---
title: "Resources"
format: html
editor: visual
---

All of the following is what was used to build our website:

## Quarto Websites

### Tutorials

- Data Science Portfolio with Quarto by Deepsha Menghani - 1/24/23
  - [YouTube Video](https://www.youtube.com/watch?v=xtSFXtDf4cM)
  - [Presentation Slides](https://deepshamenghani.quarto.pub/portfolio-with-quarto-workshop/#/title-slide)
- Workshop Wednesdays October 2022: Creating personal websites with Quarto by CCT Data Science - 10/26/22
  - [YouTube Video](https://youtu.be/GsoBkxrK9Vg?si=BMPG5UFepM6_tt8R)
  - [Presentation Slides](https://viz.datascience.arizona.edu/quarto-websites/quarto-websites.html#/personal-websites-with-quarto)
  - [GitHub Repository](https://github.com/cct-datascience/CALS-workshops/tree/main/202210-quarto-website)
- Publish a Quarto website with Netlify by Jadey Ryan - 11/19/23
  - [Blog Post](https://jadeyryan.com/blog/2023-11-19_publish-quarto-website/)
- Beautiful reports and presentations with Quarto | Led by Tom Mock, RStudio by Posit PBC - 9/27/22
  - [YouTube Video](https://www.youtube.com/watch?v=hbf7Ai3jnxY&list=PLNuj1Dnarqy7ovHFrKTYDuD545QuaTkpA&index=3)
  - [GitHub Repository](https://github.com/jthomasmock/quarto-reporting)
  - [Presentation Slides](https://thomasmock.quarto.pub/reports-presentations/)
- Just enough CSS (and Sass) for data scientists by Sam Csik - 8/3/23
  - [Presentation Slides](https://samanthacsik.github.io/just-enough-css-sass/#/title-slide)
  - [GitHub Repository](https://github.com/samanthacsik/just-enough-css-sass)
- Official Quarto Documentation - Creating a Website
  - [Online Book](https://quarto.org/docs/websites/)

### Examples

- Jadey Ryan - Environmental Data Scientist ([Website](https://jadeyryan.com/)) ([GitHub Repository](https://github.com/jadeynryan/jadey_website))
- Samantha Csik - Data Training Coordinator ([Website](https://samanthacsik.github.io/)) ([GitHub Repository](https://github.com/samanthacsik/samanthacsik.github.io/tree/main))
- Drew Dimmery - Professor of Data Science for the Common Good ([Website](https://ddimmery.com/)) ([GitHub Repository](https://github.com/ddimmery/quarto-website))
- Nick Lyon - Data Scientist ([Website](https://njlyon0.github.io/)) ([Github Repository](https://github.com/njlyon0/njlyon0.github.io))
- Ted Laderas - Bioinformatics Trainer and Data Science Mentor ([Website](https://laderast.github.io/)) ([Github Repository](https://github.com/laderast/laderast.github.io))
- Jessica S. Guo - Plant Ecophysiologist and Data Scientist ([Website](https://jessicaguo.github.io/)) ([Github Repository](https://github.com/jessicaguo/jessicaguo.github.io))
- Hertie Coding Club ([Website](https://www.hertiecodingclub.com/)) ([Github Repository](https://github.com/jurjoroa/hcc-website))

## Quarto Extensions

Icons:

- [Font Awesome](https://github.com/quarto-ext/fontawesome)
- [Academicons](https://github.com/schochastics/academicons)
- [Bootstrap Icons](https://github.com/shafayetShafee/bsicons)

## Styling

- [Google Fonts](https://fonts.google.com/)
- [Quarto Sass Variables](https://quarto.org/docs/output-formats/html-themes.html#sass-variables)
= [Coolors Color Palette Generator](https://coolors.co/)