---
title: "Research"
format: html
editor: visual
---

## My group currently has a number of interdisciplinary projects under three research themes:

### Social-ecological systems modeling, valuation, and decision science

How will environmental changes (i.e., land use change, climate change, ocean acidification, invasive species) impact the ecosystem goods and services provided by Hawaiʻi’s ecosystems, and what are the consequence for human wellbeing?

How do land management practices affecting erosion, groundwater recharge, and water quality impact ecosystem services across the watershed, from mountain ridge to coral reef? Where are there trade-offs and win-win opportunities? How can we apply economics and decision science to make better decisions?

### Marine management

What are the socio-economic impacts of Palau’s National Marine Sanctuary?

### Natural capital and green accounting

What is the true progress of Hawaii, measured using the Genuine Progress Indicator? 

What stocks of natural capital does Hawaii have, and what ecosystem services flow from these?

## Support and Recognition

My lab’s research has been supported by NOAA, USGS, the Pacific Island Climate Adaptation Science Center, USDA, National Geographic Pristine Seas, the Moore Foundation, Ulupono Initiative, the Hawaiʻi State Department of Health, the Hawaiʻi Department of Economic Development, Business, and Tourism, and others. Most recently, I was awarded a Pew Marine Fellowship.